"""Collect licenses of modules linked into either standalone release binary."""

import json
import os
from pathlib import Path
import subprocess


ROOT = Path(__file__).resolve().parents[1]


def collect():
    modules = {}
    for target in ("windows", "linux"):
        env = {**os.environ, "GOOS": target, "GOARCH": "amd64", "CGO_ENABLED": "0"}
        output = subprocess.check_output(
            ["go", "list", "-deps", "-json=Module", "."],
            cwd=ROOT, env=env, text=True, encoding="utf-8")
        decoder = json.JSONDecoder()
        remaining = output.lstrip()
        while remaining:
            package, end = decoder.raw_decode(remaining)
            module = package.get("Module")
            if module and not module.get("Main"):
                modules[module["Path"]] = module.get("Replace", module)
            remaining = remaining[end:].lstrip()
    sections = ["Third-party notices for the Windows and Linux standalone binaries.\n"
                "Generated by tests/package_licenses.py from linked module dependencies.\n"]
    goroot = subprocess.check_output(["go", "env", "GOROOT"], cwd=ROOT,
                                     text=True, encoding="utf-8").strip()
    sources = [("Go runtime and standard library", Path(goroot), [Path(goroot) / "LICENSE"])]
    for path, module in sorted(modules.items()):
        directory = Path(module["Dir"])
        licenses = sorted(p for p in directory.rglob("*") if p.is_file()
                          and p.name.upper().split(".")[0] in {"LICENSE", "LICENCE", "COPYING", "NOTICE"}
                          and not any(part in {"testdata", ".git"} for part in p.relative_to(directory).parts))
        if not licenses:
            raise RuntimeError("No license found for " + path)
        sources.append((path + " " + module.get("Version", "(local replacement)"), directory, licenses))
    for name in ("krbgss", "krbclient"):
        directory = ROOT / "internal" / name
        sources.append(("Local adaptation: internal/" + name, directory, [directory / "LICENSE"]))
    for title, directory, files in sources:
        sections.append("\n" + "=" * 78 + "\n" + title + "\n" + "=" * 78 + "\n")
        for path in files:
            sections.append("\n--- " + path.relative_to(directory).as_posix() + " ---\n"
                            + path.read_text(encoding="utf-8").rstrip() + "\n")
    destination = ROOT / "bin" / "THIRD-PARTY-LICENSES.txt"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text("".join(sections), encoding="utf-8", newline="\n")
    print(f"Packaged {len(modules)} linked module licenses, Go and two local adaptations: {destination}")


if __name__ == "__main__":
    collect()
